// WeatherTimeline.jsx — Antarctic Weather Event Timeline Component
// Displays real-time and historical weather events with newest events first

import React, { useMemo, useState } from "react";
import {
  AlertTriangle,
  ChevronDown,
  ChevronUp,
  Clock,
  Gauge,
  Radio,
  ShieldAlert,
  Snowflake,
  Thermometer,
  TrendingDown,
  Wind,
  Zap,
} from "lucide-react";

/**
 * WeatherTimeline Component
 *
 * Renders chronological meteorological events generated by the Weather Event Engine.
 *
 * @param {object} props
 * @param {Array<object>} props.events - Weather events array (each with id, timestamp, severity, station, description)
 * @param {string} [props.activeStation] - Currently selected station ID
 * @param {number} [props.maxVisible=6] - Max items displayed before scroll
 */
export function WeatherTimeline({
  events = [],
  activeStation = null,
  maxVisible = 6,
}) {
  const [filter, setFilter] = useState("ALL"); // "ALL" | "CRITICAL" | "WARNING" | "STATION"
  const [isExpanded, setIsExpanded] = useState(true);

  // Filter events based on active selection and ensure sorted newest first
  const filteredEvents = useMemo(() => {
    const sorted = [...events].sort(
      (a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()
    );

    if (filter === "CRITICAL") {
      return sorted.filter((e) => e.severity === "CRITICAL");
    }
    if (filter === "WARNING") {
      return sorted.filter((e) => e.severity === "WARNING" || e.severity === "CRITICAL");
    }
    if (filter === "STATION" && activeStation) {
      return sorted.filter((e) => e.station === activeStation);
    }
    return sorted;
  }, [events, filter, activeStation]);

  const counts = useMemo(() => {
    let critical = 0;
    let warning = 0;
    events.forEach((e) => {
      if (e.severity === "CRITICAL") critical++;
      else if (e.severity === "WARNING") warning++;
    });
    return { critical, warning, total: events.length };
  }, [events]);

  const getEventIcon = (type) => {
    switch (type) {
      case "HIGH_WIND":
        return <Wind size={13} className="event-icon wind" />;
      case "EXTREME_COLD":
        return <Thermometer size={13} className="event-icon cold" />;
      case "PRESSURE_DROP":
        return <TrendingDown size={13} className="event-icon pressure" />;
      case "SEVERE_WEATHER":
        return <ShieldAlert size={13} className="event-icon severe" />;
      default:
        return <Radio size={13} className="event-icon nominal" />;
    }
  };

  const formatEventTime = (isoString) => {
    try {
      const d = new Date(isoString);
      return d.toLocaleTimeString([], {
        hour: "2-digit",
        minute: "2-digit",
        second: "2-digit",
      });
    } catch {
      return "LIVE";
    }
  };

  return (
    <div className="weather-timeline-box">
      {/* Timeline Header */}
      <div className="weather-timeline-head">
        <div className="timeline-title-group">
          <Clock size={13} className="blue-icon" />
          <span>WEATHER EVENT TIMELINE</span>
          <span className="timeline-count-chip">{filteredEvents.length}</span>
        </div>

        <div className="timeline-badges-group">
          {counts.critical > 0 && (
            <span className="timeline-status-pill pill-critical">
              <span className="pulse-dot red" /> {counts.critical} CRITICAL
            </span>
          )}
          {counts.warning > 0 && (
            <span className="timeline-status-pill pill-warning">
              <span className="pulse-dot amber" /> {counts.warning} WARN
            </span>
          )}
          <button
            className="timeline-toggle-btn"
            onClick={() => setIsExpanded(!isExpanded)}
            title={isExpanded ? "Collapse Timeline" : "Expand Timeline"}
            aria-label="Toggle Timeline View"
          >
            {isExpanded ? <ChevronUp size={13} /> : <ChevronDown size={13} />}
          </button>
        </div>
      </div>

      {/* Filter Tabs */}
      <div className="timeline-filter-row">
        <button
          className={`filter-btn ${filter === "ALL" ? "active" : ""}`}
          onClick={() => setFilter("ALL")}
        >
          ALL ({counts.total})
        </button>
        <button
          className={`filter-btn critical ${filter === "CRITICAL" ? "active" : ""}`}
          onClick={() => setFilter("CRITICAL")}
        >
          CRITICAL ({counts.critical})
        </button>
        <button
          className={`filter-btn warning ${filter === "WARNING" ? "active" : ""}`}
          onClick={() => setFilter("WARNING")}
        >
          WARNINGS ({counts.warning})
        </button>
        {activeStation && (
          <button
            className={`filter-btn ${filter === "STATION" ? "active" : ""}`}
            onClick={() => setFilter("STATION")}
          >
            {activeStation}
          </button>
        )}
      </div>

      {/* Chronological Event Stream (Newest First) */}
      {isExpanded && (
        <div className="timeline-event-stream">
          {filteredEvents.length === 0 ? (
            <div className="timeline-empty-state">
              <Snowflake size={14} className="blue-icon" />
              <span>NO ANOMALOUS WEATHER EVENTS DETECTED IN THIS WINDOW</span>
            </div>
          ) : (
            filteredEvents.map((evt) => {
              const severityTone =
                evt.severity === "CRITICAL"
                  ? "critical"
                  : evt.severity === "WARNING"
                  ? "warning"
                  : "nominal";

              return (
                <div
                  key={evt.id}
                  className={`timeline-event-card tone-${severityTone}`}
                >
                  <div className="event-marker-col">
                    <span className={`event-marker-dot ${severityTone}`}>
                      <i />
                    </span>
                    <div className="event-connector-line" />
                  </div>

                  <div className="event-card-body">
                    <div className="event-card-top">
                      <div className="event-title-line">
                        {getEventIcon(evt.type)}
                        <b className="event-title-text">{evt.title}</b>
                        <span className={`event-station-tag ${evt.station?.toLowerCase()}`}>
                          {evt.station}
                        </span>
                      </div>

                      <div className="event-meta-right">
                        <time className="event-time">
                          {formatEventTime(evt.timestamp)}
                        </time>
                        <span className={`event-severity-badge ${severityTone}`}>
                          {evt.severity}
                        </span>
                      </div>
                    </div>

                    <p className="event-description">{evt.description}</p>

                    {evt.metric && (
                      <div className="event-metric-footer">
                        <span>DETECTION METRIC:</span>
                        <b>{evt.metric}</b>
                      </div>
                    )}
                  </div>
                </div>
              );
            })
          )}
        </div>
      )}
    </div>
  );
}

export default WeatherTimeline;
